default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Deploy a new version to the App Store"
  lane :release do
     update_code_signing_settings(
           use_automatic_signing: true,
           code_sign_identity: "iPhone Developer",
           bundle_identifier: "com.xebni.appci",
     )
#      disable_automatic_code_signing(path: "appci.xcodeproj")
#
#      enable_automatic_code_signing(path: "appci.xcodeproj")
     build_app(xcargs: "-allowProvisioningUpdates")
     upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
