default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Deploy a new version to the App Store"
  lane :release do
     match(type: 'appstore')
     build_app
     upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
