name: iOS starter workflow

on:
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Echo
        run: |
          echo hello git-action
      - name: NPM
        run: |
          npm -v
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy-ios
        run: fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

